---
title: "Assignment 2"
author: "Daniel Stewart"
date: "September 23, 2019"
output: html_document
---

 Loading Packages
```{r load packages, warning = FALSE, echo = FALSE}
library(gapminder)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(tibble)
library(data.table)
library(DT) #note that I could not export to git_document due to DT 
library(datasets)
```

#Exercise 1

Exercise 1.1
```{r}
gapminder %>%
  filter(country == 'Denmark' | country == 'Greece' | country == 'Nepal',
         year ==  1972)
```
Exercise 1.2
```{r}
gapminder %>%
  filter(country == 'Denmark' | country == 'Greece' | country == 'Nepal',
         year ==  1972) %>%
  select(country, gdpPercap)
```

Exercise 1.3
```{r}
gapminder %>%
  group_by(country) %>%
  mutate(LifeExpDiff = lifeExp - lag(lifeExp)) %>%
  filter(LifeExpDiff < 0)
```

Exercise 1.4
```{r}
gapminder %>%
  group_by(country) %>%
  summarise(max(gdpPercap)) 
```
Exercise 1.5
```{r}
gapminder %>%
  filter(country == "Canada") %>%
  select(lifeExp, gdpPercap) %>%
  ggplot +
  geom_point(aes(x = gdpPercap, y = lifeExp)) +
  xlab("GDP Per Capita") +
  ylab("Life Expectancy") + 
  scale_x_log10()
```

#Exercise 2

```{r}

#Identifying the most extreme values for both variables (range)
gapminder %>%
  select(country, pop) %>%
  summarise(max(pop), min(pop),
            first(country), last(country)) 

#Creating a list of countries included in the dataset (Nominal range)
datatable(gapminder %>%
  select(country) %>%
  distinct(country, .keep_all= TRUE)) 

#Visualizing the population data distribution from 1952-2007 (spread, distribution)
  ggplot(gapminder) +
  geom_boxplot (aes(factor(year), pop)) +
  xlab("Year") +
  ylab("Population") + 
  scale_y_log10() 

#Visualizing the global increase in population from 1952 - 2007 (yearly global change)
ggplot(gapminder, aes(year, pop)) +
  geom_bar(stat = "identity")  +
  xlab("Year") +
  ylab("Global Population") 


```

#Exercise 3

Viewing data before plot creation
```{r}
library(datasets) #loading and assessing data prior to plot creation
data(iris)
summary(iris)
```

Plot 1: Looking at relationships between sepal length and pedal length of multiple iris species
```{r}
iris %>%
  ggplot() +
  geom_point (aes(Sepal.Length, Petal.Length, color=Species)) +
  xlab("Iris Species") +
  ylab("Petal Width") +
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
```



Plot 2: Comparing petal widths of multiple iris species
```{r}
iris %>%
  ggplot() +
  geom_boxplot (aes(Species, Petal.Width)) +
  xlab("Iris Species") +
  ylab("Petal Width") + 
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```



